[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Daniel Keep <daniel.keep@gmail.com>"]

[dependencies]
clap = "1.5.3"
crossbeam = "0.1.6"
lazy_static = "0.1.15"
regex = "0.1.43"
rust-crypto = "0.2.34"
strcursor = "0.1.0"
time = "0.1.34"
